project:
  type: website
  output-dir: docs  # ‚Üê this is important


website:
  title: 'Caleb Rother'
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: Student.qmd
        text: Campus Involvement and Improvement
      - href: CV.qmd
        text: CV
format:
  html:
    theme: cosmo # or: flatly, minty, journal, litera, sketchy, darkly, etc
    css: styles.css

resources:
  - images/**
  - CV.pdf
  - ShadePark.pdf
  - AIMSPaper.pdf
  - Goldwater2025.pdf
